import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    absolute: "Next.js App",
    default: "Next App",
    template: "%s | Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-xl`}
      >
        <header className="p-4 bg-blue-500">
          <p>This is the header</p>
        </header>
        <main>{children}</main>
        <footer className="p-4 bg-gray-500">
          <p>This is the footer</p>
        </footer>
      </body>
    </html>
  );
}
